-- MySQL Script generated by MySQL Workbench
-- 12/03/15 10:37:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`perfil` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `perfil_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_perfil1_idx` (`perfil_id` ASC),
  CONSTRAINT `fk_usuario_perfil1`
    FOREIGN KEY (`perfil_id`)
    REFERENCES `mydb`.`perfil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`continente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`continente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pais` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `continente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pais_continente1_idx` (`continente_id` ASC),
  CONSTRAINT `fk_pais_continente1`
    FOREIGN KEY (`continente_id`)
    REFERENCES `mydb`.`continente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `pais_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_estado_pais1_idx` (`pais_id` ASC),
  CONSTRAINT `fk_estado_pais1`
    FOREIGN KEY (`pais_id`)
    REFERENCES `mydb`.`pais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `estado_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cidade_estado1_idx` (`estado_id` ASC),
  CONSTRAINT `fk_cidade_estado1`
    FOREIGN KEY (`estado_id`)
    REFERENCES `mydb`.`estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bairro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bairro` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cidade_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bairro_cidade1_idx` (`cidade_id` ASC),
  CONSTRAINT `fk_bairro_cidade1`
    FOREIGN KEY (`cidade_id`)
    REFERENCES `mydb`.`cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rua`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rua` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `bairro_id` INT NOT NULL,
  `velocidade` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rua_bairro1_idx` (`bairro_id` ASC),
  CONSTRAINT `fk_rua_bairro1`
    FOREIGN KEY (`bairro_id`)
    REFERENCES `mydb`.`bairro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`localizacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`localizacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `latitude` VARCHAR(45) NOT NULL,
  `longitude` VARCHAR(45) NOT NULL,
  `rua_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_localizacao_rua1_idx` (`rua_id` ASC),
  CONSTRAINT `fk_localizacao_rua1`
    FOREIGN KEY (`rua_id`)
    REFERENCES `mydb`.`rua` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`buraco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`buraco` (
  `localizacao_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `confirmado` TINYINT(1) NOT NULL,
  `foto` BLOB NULL,
  `data` DATE NOT NULL,
  `data_fechado` DATE NULL,
  PRIMARY KEY (`localizacao_id`, `usuario_id`, `data`),
  INDEX `fk_buraco_localizacao1_idx` (`localizacao_id` ASC),
  INDEX `fk_buraco_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_buraco_localizacao1`
    FOREIGN KEY (`localizacao_id`)
    REFERENCES `mydb`.`localizacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_buraco_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_de_acidente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_de_acidente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`acidente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`acidente` (
  `idacidente` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `localizacao_id` INT NOT NULL,
  `tipo_de_acidente_id` INT NOT NULL,
  PRIMARY KEY (`idacidente`),
  INDEX `fk_acidente_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_acidente_localizacao1_idx` (`localizacao_id` ASC),
  INDEX `fk_acidente_tipo_de_acidente1_idx` (`tipo_de_acidente_id` ASC),
  CONSTRAINT `fk_acidente_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_acidente_localizacao1`
    FOREIGN KEY (`localizacao_id`)
    REFERENCES `mydb`.`localizacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_acidente_tipo_de_acidente1`
    FOREIGN KEY (`tipo_de_acidente_id`)
    REFERENCES `mydb`.`tipo_de_acidente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_fiscalizacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_fiscalizacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `periodo_de_visualizacao` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fiscalização`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fiscalização` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `localizacao_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `confirmado` TINYINT(1) NOT NULL DEFAULT 0,
  `tipo_de_fiscalizacao_id` INT NOT NULL,
  `data` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_fiscal_eletronica_localizacao1_idx` (`localizacao_id` ASC),
  INDEX `fk_fiscal_eletronica_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_fiscal_eletronica_tipo_de_fiscalizacao1_idx` (`tipo_de_fiscalizacao_id` ASC),
  CONSTRAINT `fk_fiscal_eletronica_localizacao1`
    FOREIGN KEY (`localizacao_id`)
    REFERENCES `mydb`.`localizacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fiscal_eletronica_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fiscal_eletronica_tipo_de_fiscalizacao1`
    FOREIGN KEY (`tipo_de_fiscalizacao_id`)
    REFERENCES `mydb`.`tipo_fiscalizacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tela`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tela` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tela_has_perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tela_has_perfil` (
  `tela_id` INT NOT NULL,
  `perfil_id` INT NOT NULL,
  PRIMARY KEY (`tela_id`, `perfil_id`),
  INDEX `fk_tela_has_perfil_perfil1_idx` (`perfil_id` ASC),
  INDEX `fk_tela_has_perfil_tela1_idx` (`tela_id` ASC),
  CONSTRAINT `fk_tela_has_perfil_tela1`
    FOREIGN KEY (`tela_id`)
    REFERENCES `mydb`.`tela` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tela_has_perfil_perfil1`
    FOREIGN KEY (`perfil_id`)
    REFERENCES `mydb`.`perfil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
